[tool.poetry]
name = "py-bas-canvas-inspector-automator"
version = "0.1.0"
description = ""
authors = ["sergerdn <64213648+sergerdn@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
playwright = { extras = ["chromium"], version = "^1.51.0" }
httpx = { extras = ["socks"], version = "^0.28.1" }
pydantic = "^2.10.6"
python-dotenv = "^1.0.1"
filelock = "^3.18.0"
psutil = "^7.0.0"
types-psutil = "^7.0.0.20250218"
mimesis = "^18.0.0"
pytesseract = "^0.3.13"

[tool.poetry.group.dev.dependencies]
pytest-playwright = "^0.7.0"
pytest = "^8.3.5"
commitizen = "^4.4.1"
pywinauto = "^0.6.9"
black = "^25.1.0"
mypy = "^1.15.0"
flake8 = "^7.1.2"
pylint = "^3.3.5"
pylint-pydantic = "^0.3.5"
types-pillow = "^10.2.0.20240822"


[tool.black]
line-length = 120

[tool.isort]
line_length = 120
py_version = 311

[tool.mypy]
python_version = "3.11"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
disallow_untyped_calls = true
#exclude = "tests/contrib"

[tool.pylint]
max-line-length = 120
min-similarity-lines = 8
ignore-imports = true

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
