[tool.poetry]
name = "py-bas-canvas-inspector-automator"
version = "0.1.0"
description = ""
authors = ["sergerdn <64213648+sergerdn@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
playwright = { extras = ["chromium"], version = "1.52.0" }
httpx = { extras = ["socks"], version = "0.28.1" }
pydantic = "2.11.4"
python-dotenv = "1.1.0"
filelock = "3.18.0"
psutil = "7.0.0"
types-psutil = "7.0.0.20250801"
mimesis = "18.0.0"
pytesseract = "0.3.13"

[tool.poetry.group.dev.dependencies]
pytest-playwright = "0.7.0"
pytest = "8.3.5"
commitizen = "4.8.0"
pywinauto = "0.6.9"
black = "25.1.0"
mypy = "1.15.0"
flake8 = "7.2.0"
pylint = "3.3.7"
pylint-pydantic = "0.3.5"
types-pillow = "10.2.0.20240822"
docformatter = "1.7.7"
docconvert = "2.2.0"

[tool.black]
line-length = 120

[tool.isort]
line_length = 120
py_version = 311

[tool.mypy]
python_version = "3.11"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
disallow_untyped_calls = true
#exclude = "tests/contrib"

[tool.pylint]
max-line-length = 120
min-similarity-lines = 8
ignore-imports = true

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
